services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [jupyter, lab]
    environment:
      SHELL: /bin/bash
      ACTIVELOOP_TOKEN: ${ACTIVELOOP_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: ["--ip='0.0.0.0'", "--port=8888", "--no-browser", "--allow-root"]
    ports:
      - 127.0.0.1:${JUPYTER_LAB_PORT-8888}:8888
    restart: always
